### PR TITLE
Change globalVariables usage

### PR DESCRIPTION
**Pull request by JSchoenbachler**

### CODE REVIEW

**Comment by JSchoenbachler** [comment]
@jakejh @ehoutland This had one instance where I'm assuming "defaultDispFunc" actually needed to be a globalVariable. I will be updating the DESCRIPTION and NEWS shortly.

**Comment by JSchoenbachler** [comment]
Also sorry for the name, I know you wanted the new naming convention but I had already named this locally yesterday before you said that.

**Comment by jakejh** [comment]
defaultDispFunc is not a global variable, it's a function that's stored in /data. I took the unusual step of making the code `simphony::defaultDispFunc`, which seems to work.

**Review by jakejh — APPROVED** [review]

**Comment by JSchoenbachler** [comment]
Okay, once @ehoutland approves I'll merge!

**Pull request merged**
