### PR TITLE
Exclude NEWS.md

### PR DESCRIPTION
**Pull request by JSchoenbachler**

### CODE REVIEW

**Comment by jakejh** [comment]
Missing a dollar sign at the end to specify end of line.

**Comment by JSchoenbachler** [comment]
@jakejh Done, sorry. I wasn't aware you had to have that, so it's now done on all other packages!

**Comment by jakejh** [comment]
Thanks. It technically still would've worked in our case. The key point is that, unlike .gitignore, .Rbuildignore interprets every line as a regex. Better to be consistent and explicit.

**Comment by jakejh** [comment]
Did you mean to close this without merging?

**Comment by JSchoenbachler** [comment]
Okay that makes sense! And no, I accidentally must have clicked "close and comment" instead of just comment. Reopened!

**Pull request merged**
